services:
  api:
    build:
      context: ./src/api
    container_name: api
    environment:
      - FOO=bar
  web:
    build:
      context: ./src/web
    container_name: web
    ports:
      - "8000:8080"
    depends_on:
      - api
  
  # Run once (on-demand)
  # docker compose --profile tools run --rm mcp-client
  mcp-client:
    build:
      context: ./src/cli/mcp
    container_name: mcp-client
    environment:
      - BASE_URL=http://web:8080
    depends_on:
      - web
    profiles:
      - tools
